services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MEDIAESSENZ\Mail\:
    resource: '../Classes/*'

  MEDIAESSENZ\Mail\Mail\Mailer:
    public: true

  MEDIAESSENZ\Mail\Service\MailService:
    public: true

  MEDIAESSENZ\Mail\Service\MailerService:
    public: true

  MEDIAESSENZ\Mail\Service\RecipientService:
    public: true

  MEDIAESSENZ\Mail\Service\ImportService:
    public: true

  MEDIAESSENZ\Mail\Command\SpoolSendCommand:
    tags:
      - name: 'console.command'
        command: 'mail:spool:send'
        description: 'Process newsletter sending queue.'

  MEDIAESSENZ\Mail\Command\MassMailingCommand:
    tags:
      - name: 'console.command'
        command: 'mail:mass-mailing'
        description: 'Add scheduled newsletters to sending queue.'

  MEDIAESSENZ\Mail\Command\AnalyzeBounceMailCommand:
    tags:
      - name: 'console.command'
        command: 'mail:analyze-bounce-mail'
        description: 'Analyze bounced newsletters from a configured mailbox.'
