services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MEDIAESSENZ\Mail\:
    resource: '../Classes/*'

  MEDIAESSENZ\Mail\Mail\Mailer:
    public: true

  MEDIAESSENZ\Mail\Hooks\PageTreeRefresh:
    public: true

  MEDIAESSENZ\Mail\Service\MailerService:
    public: true

  MEDIAESSENZ\Mail\Service\RecipientService:
    public: true

  MEDIAESSENZ\Mail\Service\ImportService:
    public: true

  MEDIAESSENZ\Mail\Command\SpoolSendCommand:
    tags:
      - name: 'console.command'
        command: 'mail:spool:send'
        description: 'Process newsletter sending queue.'

  MEDIAESSENZ\Mail\Command\MassMailingCommand:
    tags:
      - name: 'console.command'
        command: 'mail:mass-mailing'
        description: 'Add scheduled newsletters to sending queue.'

  MEDIAESSENZ\Mail\Command\AnalyzeBounceMailCommand:
    tags:
      - name: 'console.command'
        command: 'mail:analyze-bounce-mail'
        description: 'Analyze bounced newsletters from a configured mailbox.'

  MEDIAESSENZ\Mail\Command\ClearScssParserCacheCommand:
    tags:
      - name: 'console.command'
        command: 'mail:clear-scss-parser-cache'
        description: 'Clears all css and meta files generated by the scss parser.'

  MEDIAESSENZ\Mail\EventListener\AddUpperCaseMarkers:
    tags:
      - name: 'event.listener'
        identifier: 'addUpperCaseMarkers'

  MEDIAESSENZ\Mail\EventListener\ManipulateFrontendUserRecipient:
    tags:
      - name: 'event.listener'
        identifier: 'manipulateFrontendUserRecipient'
        before: 'normalizeRecipientData'

  MEDIAESSENZ\Mail\EventListener\ManipulateAddressRecipient:
    tags:
      - name: 'event.listener'
        identifier: 'manipulateAddressRecipient'
        before: 'normalizeRecipientData'

  MEDIAESSENZ\Mail\EventListener\NormalizeRecipientData:
    tags:
      - name: 'event.listener'
        identifier: 'normalizeRecipientData'

  MEDIAESSENZ\Mail\EventListener\SimulateFrontendUserGroup:
    tags:
      - name: 'event.listener'
        identifier: 'simulateFrontendUserGroup'

  MEDIAESSENZ\Mail\Property\TypeConverter\DateTimeImmutableConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: DateTimeImmutable
        sources: int,string,array

  MEDIAESSENZ\Mail\ContentObject\EmogrifierContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'EMOGRIFIER'

  MEDIAESSENZ\Mail\ContentObject\ScssContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'SCSS'
