services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MEDIAESSENZ\Mail\:
    resource: '../Classes/*'

  MEDIAESSENZ\Mail\Service\MailerService:
      public: true

  MEDIAESSENZ\Mail\Command\InvokeMailerEngineCommand:
    tags:
      - name: 'console.command'
        command: 'mail:invoke-mailer-engine'
        description: 'Invoke Mailer Engine of EXT:mail'
  MEDIAESSENZ\Mail\Command\MailCommand:
    tags:
      - name: 'console.command'
        command: 'mail:mailing-queue'
        description: 'This command invokes mail in order to process queued messages.'
  MEDIAESSENZ\Mail\Command\AnalyzeBounceMailCommand:
    tags:
      - name: 'console.command'
        command: 'mail:analyze-bounce-mail'
        description: 'This command will get bounce mail from the configured mailbox.'
