services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MEDIAESSENZ\Mail\:
    resource: '../Classes/*'

  MEDIAESSENZ\Mail\Mail\Mailer:
    public: true

  MEDIAESSENZ\Mail\Hooks\PageTreeRefresh:
    public: true

  MEDIAESSENZ\Mail\Service\MailerService:
    public: true

  MEDIAESSENZ\Mail\Service\RecipientService:
    public: true

  MEDIAESSENZ\Mail\Command\SpoolSendCommand:
    tags:
      - name: 'console.command'
        command: 'mail:spool:send'
        description: 'Process newsletter sending queue.'

  MEDIAESSENZ\Mail\Command\MassMailingCommand:
    tags:
      - name: 'console.command'
        command: 'mail:mass-mailing'
        description: 'Add scheduled newsletters to sending queue.'

  MEDIAESSENZ\Mail\Command\AnalyzeBounceMailCommand:
    tags:
      - name: 'console.command'
        command: 'mail:analyze-bounce-mail'
        description: 'Analyze bounced newsletters from a configured mailbox.'

  MEDIAESSENZ\Mail\Command\ClearScssParserCacheCommand:
    tags:
      - name: 'console.command'
        command: 'mail:clear-scss-parser-cache'
        description: 'Clears all css and meta files generated by the scss parser.'

  MEDIAESSENZ\Mail\EventListener\AddUpperCaseMarkers:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/add-upper-case-markers'

  MEDIAESSENZ\Mail\EventListener\ManipulateFrontendUserRecipient:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/manipulate-frontend-user-recipient'
        before: 'mediaessenz/mail/normalize-recipient-data'

  MEDIAESSENZ\Mail\EventListener\NormalizeRecipientData:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/normalize-recipient-data'

  MEDIAESSENZ\Mail\EventListener\SimulateFrontendUserGroup:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/simulate-frontend-user-group'

  MEDIAESSENZ\Mail\EventListener\PageTreeRefresh:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/page-tree-refresh'

  MEDIAESSENZ\Mail\EventListener\AssetRenderer\PageTreeRefresh:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/asset-renderer-pagetree-refresh'
        event: TYPO3\CMS\Core\Page\Event\BeforeJavaScriptsRenderingEvent

  MEDIAESSENZ\Mail\EventListener\AddBackToMailWizardButton:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/add-back-to-mail-wizard-button'

  MEDIAESSENZ\Mail\EventListener\DeactivateFeUsers:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/deactivate-feusers'

  MEDIAESSENZ\Mail\EventListener\InvalidateCsvRecipients:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/invalidate-csv-recipients'

  MEDIAESSENZ\Mail\EventListener\InvalidatePlainRecipients:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/invalidate-plain-recipients'

  MEDIAESSENZ\Mail\EventListener\AvoidCaching:
    tags:
      - name: 'event.listener'
        identifier: 'mediaessenz/mail/avoid-caching'

  MEDIAESSENZ\Mail\Property\TypeConverter\DateTimeImmutableConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: DateTimeImmutable
        sources: int,string,array

  MEDIAESSENZ\Mail\ContentObject\EmogrifierContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'EMOGRIFIER'

  MEDIAESSENZ\Mail\ContentObject\ScssContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'SCSS'
